DROP TABLE IF EXISTS statuses;

CREATE TABLE statuses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status_id TEXT NOT NULL,
    host TEXT 
);

